spring:
  cloud:
    gateway:
      routes:
        - id: auth-routes
          uri: http://localhost:8001
          predicates:
            - Method=GET,POST,PUT,DELETE
            - Path=/api/v1/auth/**


        - id: user-routes
          uri: http://localhost:8001
          predicates:
            - Method=GET,POST,PUT,DELETE
            - Path=/api/v1/user/**
          filters:
            #            - RewritePath=/api/v1/user(?<segment>.*),/api/v1/user$\{segment}
            #            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                rate-limiter: "#{@defaultRedisRateLimiter}"
                key-resolver: "#{@ipKeyResolver}"

  application:
    name: "evergreenmedic"
  profiles:
    active: "dev"
  data:
    redis:
      port: 6379
      host: localhost
      password: "ksby871FBLS*^@3"
server:
  port: 8080




